### ISSUE TITLE
Network & Forman information

### ISSUE THREAD

**Issue by YonatanGolick** [CCI-MOC/rubicon-issues#4] opened 2020-12-03 07:23 UTC

**Comment by Rmaabari** [comment] 2020-12-06 12:45
Need more information regarding the network of the machines from @naved001.

1. after installing the Foreman management tool, we reached the foreman UI, from there we need some network information on your side, such as, which to configure and set up on our DHCP & DNS on the foreman host.
also, we've tried to create a new host via the foreman web interface and encounter some more networking information needed relating to the nodes os provisioning.

2. Do we need first to set up a DHCP&DNS so we can provide the foreman with IP address?

if possible I would like to receive a formative network configuration table regarding the entire setup.  
 
here's a screenshot of the networking information needed when provisioning a node via foreman UI.
![interface](https://user-images.githubusercontent.com/74144712/101279739-01072180-37cd-11eb-9c9d-bdc4e3241001.png)
 
 

Thanks in advance.

**Comment by naved001** [comment] 2020-12-07 00:01
I am not very experienced with Foreman specific things. I am just gonna post what I sent over in the email for visibility. 

> The foreman host has 3 network interfaces.
> 
> 10.30.4.0/24 dev ens4 proto kernel scope link src 10.30.4.1 metric 104
> 10.30.5.0/24 dev ens5 proto kernel scope link src 10.30.5.1 metric 105
> 129.10.5.0/24 dev ens3 proto kernel scope link src 129.10.5.144 metric 103
> 
> ens3 gives it the public IP, ens4 is on private VLAN 304 and ens5 is on private VLAN 305. 
> I configured ens4 and ens5 with some IPs so I could test connectivity between this host and the power9 servers. 
> Please feel free to change those to whatever network CIDR you prefer.
> 
> The network configuration of the power9 servers is as follows:
> 
> bu-21-5:
> 
> enp1s0f0 (lower mac address) - access mode VLAN 304, some networking issues, working on figuring it out
> enp1s0f1 (higher mac address) - access mode VLAN 305, some networking issues, working on figuring it out
> 
> bu-21-6:
> 
> enp1s0f0 (ec:0d:9a:82:de:9e) - access mode VLAN 304, some networking issues, working on figuring it out
> enp1s0f1 (ec:0d:9a:82:de:9f) - access mode VLAN 305
> 
> bu-21-7:
> 
> enp1s0f0 (50:6b:4b:fb:4e:52) - access mode VLAN 304
> enp1s0f1 (50:6b:4b:fb:4e:53) - access mode VLAN 305

So there are 2 private VLANs (VLAN 304 and VLAN 305) that you have full access to, so your foreman server can run DHCP/DNS on those networks; that means you get to decide the IPv4 subnet and address. 

> Do we need first to set up a DHCP&DNS so we can provide the foreman with IP address?

Foreman does provide, among other things, DHCP and DNS. So there should be no need to set those up separately.

I provided mac-addresses for two of the hosts, but you can easily find out the mac address of the 3rd host's interfaces from the BMC.

I would recommend trying to pxe boot bu-21-7 to begin with since both of its network interfaces have no issues. I am still in the middle of resolving the networking issues on the other 2 hosts.

I have taken this Monday off but if you'd like we can schedule a call this Tuesday.

**Comment by Rmaabari** [comment] 2020-12-07 09:06
Thank you @naved001 for your information.
we would appreciate if we could schedule a call this Tuesday, we aren't much familiar with the BMC interface, a quick online tour with you could be great and helpful.

**Comment by naved001** [comment] 2020-12-10 00:12
Hi guys,

I am a foreman noob so my foreman specific instructions won't be very good. I have only booted the power9s using MaaS since that's pretty simple to use, but my impression was that you guys would prefer foreman. 

Let's say if you wanted to provision an OS on bu-21-7. First thing is to make sure that it boots from the right interface. Start by tunneling the IPMI traffic via the ipmi gateway that we have setup (rubicone.hil.massopen.cloud). Then visit the IPMI address in the browser for bu-21-7 which is `10.0.21.7`. Login with the credentials (lookup defaults for openbmc).

Once logged in, you'll see that you can control most things about the node (power cycle, sol console, etc).

![image](https://user-images.githubusercontent.com/20113064/101702390-c0b6d600-3a4e-11eb-86e2-ecbd7d98cc92.png)

From there go to "Serial over LAN console"

![image](https://user-images.githubusercontent.com/20113064/101703561-cca39780-3a50-11eb-958a-5faa15258274.png)

This will allow to you go into the "BIOS" equivalent of this system to manage boot devices and other settings. 

Since the node has 2 nics.
enp1s0f0 (50:6b:4b:fb:4e:52) - access mode VLAN 304
enp1s0f1 (50:6b:4b:fb:4e:53) - access mode VLAN 305
You can boot from either of those, but let's stick with VLAN 304 for being the provisioning VLAN. 

![image](https://user-images.githubusercontent.com/20113064/101703627-f2c93780-3a50-11eb-83c5-94b888c5d541.png)

Then on your foreman instance, you'll create an IPv4 Subnet for provisioning. That subnet will be whatever is corresponding to the foreman interface connected to VLAN 304 (ens4 in this case). You'll also create a local domain (e.g. `rubicone.moc`)

`10.30.4.0/24 dev ens4 proto kernel scope link src 10.30.4.1 metric 104`

In the screenshot posted earlier, you'll put the boot mac address of bu-21-7 which will be `50:6b:4b:fb:4e:52`. You will choose a DNS name (something like `bu-21-7.rubicone.moc`) and assign it an IP address. You'll choose an operating system and media (I think those can be inherited from host groups too). When foreman tries to boot the system, keep an eye on the sol console to see what's going on, there's an OS on the disk so if the node fails to pxe boot, then it will boot from the disk into Ubuntu.

Here's some more screenshot from our foreman instance that has been used to provision the power9 servers, though that foreman instance is not managed by me but this may help.

We have a power9 host group, so hosts under that group will inherit some configuration.

This shows the networking:
![image](https://user-images.githubusercontent.com/20113064/101703829-60756380-3a51-11eb-8409-16b430afb3af.png)
Operating System:
![image](https://user-images.githubusercontent.com/20113064/101703849-6ff4ac80-3a51-11eb-9692-b58f44e8a74e.png)

This is how the host bu-21-7 shows up in our foreman instance:
![image](https://user-images.githubusercontent.com/20113064/101703979-bc3fec80-3a51-11eb-949c-b3f068d902b7.png)

**Comment by Rmaabari** [comment] 2020-12-14 16:00
Hi @naved001,
can you please provide the passwords for root user on both BMC & foreman servers and for hil user on BMC server.
Thank you.

**Comment by naved001** [comment] 2020-12-14 18:10
BMC credentials: 
username: `root`
password: `0penBmc`

The foreman host is VM, so can't arrange out of bound management access for that.

> hil user on BMC server.

not sure what you mean by that? there's no hil user to access the BMC itself.

**Comment by YonatanGolick** [comment] 2020-12-14 18:19
He meant the password to the middle-man server for the hil user + the root users password so we can add some ssh keys for some other machines.

**Comment by naved001** [comment] 2020-12-14 18:48
ah, the machine that gives you access to the IPMI network. Well, that's restricted by design so we can control what keys have access to the IPMI network. I'd be happy to add any more public keys if you share those here.

**Comment by naved001** [comment] 2020-12-14 18:59
also, there should be no password auth on that host, so I disabled password logins for the hil users altogether. (I forgot to do it earlier).

**Comment by YonatanGolick** [comment] 2020-12-15 10:42
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDOn/oWGN469aWDOi2CoMf8dTISriaK60tMWCNtsMp+9hXPjDlmagxZVLhCfRDLWcMLL5r7ZXBtPaCxziTGxmUkQdIgpC0Fo7uQiQSVVwycJ7T8b6TLXDlJSL+92V/ti7DrGpCX18Mp2UGjhKE7HtkHwieSfY6i0FsoRwSBUzVF67n5y2AU49tKtwa3FidLWjhlCn+73P2V+tiDQTybUU1qnssF+gO7lI18ZrtvsP1FkiQSmmyuNIFVyZELK4UOE2AzxBrg6TIdR6IIDuaLmTuaJN6twLDDLNhVuLbq1nsO0DQyaML8PD4ZyDiZnOybXDHsuCXyqCyKrsqT9v5JSt4gPtc6GAtvdu+UQSwliIUXBkI2vWG7mbGZCeVvDZOectKDH4qCRjZ1PAPXFlPP4zGFyZgbK6DMQ7KDkxQxWrf/YpGEPI9E8k2pPP3//NHgk9Bv3dOuI64OeOZG5bJzQuN4Uifjm590y0FFSy+MX16HNehvpuEwHaEOjtp8jkR9bWU= root@rubicone-foreman

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCx6hQg0gn2hc17qFhanBRkE/9ZjXnDALDqcTT/qH/0C3II+QrmutIUX9Rpjk/AzZfvIFXAmGck8H2wM7BrKCkEnTR2dAO/TX2rN3/Pak52aspVno9W9yUKEov9M0VG7MS3/Vz8HObF4NYqDxw8ds3Xtoch7L6ofw7YQjdVvcrwinlZvXu6Te3/vqzIBGddlmo7OzxxWjiWgr9WvkqvwvyIVFQ/+aoJT3YY6noP0RJtwPvMKQsp9KeAyvegdIk13tRPK0WHywQD/SbKci6YVphCfoVglfXBGn5sYzk+L8B0oMP7VOa1H3ewP/f69+o5owS8v94HpLD2V4UJU5FypA4f yg199@DESKTOP-74P4F95

**Comment by naved001** [comment] 2020-12-15 13:54
I have added those keys to the hil user

**Closed as completed** 2020-12-21 09:25 UTC
Labels: needs_description
